# Generated by Django 5.1.3 on 2024-12-01 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
    ]
